# Generated by Django 4.2.11 on 2025-01-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auctionlisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home', 'Home'), ('Books', 'Books'), ('Toys', 'Toys'), ('Sports', 'Sports'), ('Automotive', 'Automotive'), ('Art', 'Art'), ('Collectibles', 'Collectibles'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
